version: "3.0"

services: 

  rdbm: 
    image: mariadb:10.3.16
    environment: 
      MYSQL_ROOT_PASSWORD: devops
      MYSQL_USER: jcazorla
      MYSQL_PASSWORD: javier
      MYSQL_DATABASE: prueba
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.0.4
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1

  wordpress:
    image: wordpress
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: rdbm 
      WORDPRESS_DB_USER: jcazorla
      WORDPRESS_DB_PASSWORD: javier
      WORDPRESS_DB_NAME: prueba
    volumes:
      - wordpress:/var/www/html

volumes:
  db:
  wordpress:
